# Generated by Django 4.2.1 on 2023-06-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0005_alter_poster_image"),
        ("accounts", "0002_userprofile_favourite_film"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="favourite_film",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_film",
            field=models.ManyToManyField(related_name="favorite_film", to="films.film"),
        ),
    ]
