# Generated by Django 4.2.1 on 2023-05-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_numbers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
