# Generated by Django 4.2.1 on 2023-06-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_numbers", "0003_phonebook_delete_person"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Phonebook",
            new_name="Person",
        ),
    ]
