# Generated by Django 4.2.1 on 2023-05-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_person_remove_post_category_alter_post_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.person"
                    ),
                ),
            ],
        ),
    ]
