# Generated by Django 4.2.1 on 2023-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_email_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                (
                    "people",
                    models.ManyToManyField(related_name="addresses", to="polls.person"),
                ),
            ],
        ),
    ]
